### ISSUE TITLE
Its not a npm bug 

### ISSUE THREAD

**Issue by EloB** [seishun/node-steam-resources#10]
You can run:
`which svn`

Then:
`mv OUTPUT_PAtH_ABOVE OUTPUT_PATH_ABOVE-backup`

Then try to run `npm install csgo`

When you want to restore svn move it back.

**Comment by seishun** [comment]
So, which part confuses you? That svn can't be run if it doesn't exist?

**Comment by EloB** [comment]
Why not just put the files on your package and publish it.
Not every server/environment has `svn` and telling people who uses it that it’s a npm bug is just a lie. To find this issue took a lot of time because it’s a dependency of a dependency. I don’t get it why it need to be a svn clone. Just makes it way more advanced. I wasted 8h on this issue.

If you don’t have time to make a simple publish script I can help you with that.

Don’t mark my tickets as spam. It’s very rude!

I’m not here to fight. I just want to have solid solutions that doesn’t wastes a lot of time for everyone.

**Comment by seishun** [comment]
You don't need svn if this module is bundled ([as it should be](https://github.com/seishun/node-steam-resources#installation)). If it's not bundled, complain to the maintainers of the module that uses this module.

It seems you're conflating multiple issues here. One is that the csgo package doesn't include node_modules for some reason. The other is the npm bug where it doesn't properly handle bundled dependencies and package-lock.json. I can't help you with either.

**Comment by EloB** [comment]
It’s better to have this as `devDependency` and include the files in this package and there shouldn’t be any issue at all.
