### ISSUE TITLE
no such file or directory, open /node_modules/steam-resources/protobuf_gen/protos.csv

### ISSUE THREAD

**Issue by simonsk90** [seishun/node-steam-resources#11]
index.js contains the following:

```
var protos = parse(fs.readFileSync(__dirname + '/protobuf_gen/protos.csv', {
  encoding: 'ascii'
}), {
  columns: true
});
```

But this "protobuf_gen" folder does simply not exist.

**Comment by seishun** [comment]
Did you follow the [instructions](https://github.com/seishun/node-steam-resources#installation) when installing it?

**Comment by simonsk90** [comment]
Yes, try it out yourself.

new folder.
npm init
npm install seishun/node-steam-resources
cd node_modules/steam-resources
node index.js

**Comment by seishun** [comment]
What was the output for `npm install seishun/node-steam-resources`? And what's your npm version?

**Comment by simonsk90** [comment]
npm -v  --> 6.13.7

`npm install seishun/node-steam-resources`
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN doota@1.0.0 No description
npm WARN doota@1.0.0 No repository field.

+ steam-resources@1.2.1
added 37 packages from 34 contributors and audited 56 packages in 6.628s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by simonsk90** [comment]
Does it create the folder for you? :)

**Comment by simonsk90** [comment]
I am getting this vulnerability:
[https://www.npmjs.com/advisories/605](url)

But I don't really know how to solve this..

**Comment by seishun** [comment]
It does create the directory for me. What's your output of `ls node_modules/steam-resources`?

**Comment by simonsk90** [comment]
index.js  LICENSE  node_modules  package.json  package-lock.json  README.md  steam_language_parser

**Comment by seishun** [comment]
There's probably something wrong with your setup. Try clearing the cache or using a different machine.

**Comment by simonsk90** [comment]
> There's probably something wrong with your setup. Try clearing the cache or using a different machine.

I already did clear the cache. :(

**Comment by seishun** [comment]
It seems it didn't work because there shouldn't be a package-lock.json file. Sorry, can't help you further.
