### ISSUE TITLE
dependency not found

### ISSUE THREAD

**Issue by ghost** [seishun/node-steam-resources#15]
Trying to install `npm install dota2`

Can't find repository:

`npm ERR! prepareGitDep > steam-resources@1.2.2 prepare /home/djon/.npm/_cacache/tmp/git-clone-b419cccf
npm ERR! prepareGitDep > svn checkout https://github.com/SteamDatabase/Protobufs/trunk protobufs && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/ProtobufGen protobuf_gen && svn checkout https://github.com/SteamRE/SteamKit/trunk/Resources/SteamLanguage steam_language`

**Comment by seishun** [comment]
I can't help you with the dota2 module. Please submit an issue there.
